### PR TITLE
FIX: Doesn't append port if empty or null

### PR DESCRIPTION
**Pull request by Joozty**
https://github.com/smi2/phpClickHouse/issues/77

Please review and merge

### CODE REVIEW

**Comment by simPod** [comment]
This shouldn't have been merged before CI passed. @Joozty can you send another PR with fixed tests?

**Comment by isublimity** [comment]
This another problem, clickhouse release 18.1.0 version - broken testVersion 
I`m fix this problem

**Comment by isublimity** [comment]
add uri tests 

https://github.com/smi2/phpClickHouse/blob/master/tests/UriTest.php

**Comment by simPod** [comment]
Ah I see 👍

**Comment by Joozty** [comment]
@isublimity @simPod Hi guys, could you please release?

**Comment by isublimity** [comment]
@Joozty done, public 1.2.2

**Pull request merged**
